// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHWeaBVC8LqDblcuwrNWYTWAFYQ0RfkH0',
    appId: '1:141798440263:web:36db454c73fecc8935e062',
    messagingSenderId: '141798440263',
    projectId: 'routemate-f4e6f',
    authDomain: 'routemate-f4e6f.firebaseapp.com',
    storageBucket: 'routemate-f4e6f.appspot.com',
    measurementId: 'G-629LM0GNYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnDhPaKhKvcI8z2Qq03mgU2soHfln8o7c',
    appId: '1:141798440263:android:6e5c344019e46e7735e062',
    messagingSenderId: '141798440263',
    projectId: 'routemate-f4e6f',
    storageBucket: 'routemate-f4e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMi4I8sVVNhIWGP3eB5un9w5zykUZ_1Nk',
    appId: '1:141798440263:ios:3eb237d3ebe807bf35e062',
    messagingSenderId: '141798440263',
    projectId: 'routemate-f4e6f',
    storageBucket: 'routemate-f4e6f.appspot.com',
    iosBundleId: 'com.example.routemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMi4I8sVVNhIWGP3eB5un9w5zykUZ_1Nk',
    appId: '1:141798440263:ios:3eb237d3ebe807bf35e062',
    messagingSenderId: '141798440263',
    projectId: 'routemate-f4e6f',
    storageBucket: 'routemate-f4e6f.appspot.com',
    iosBundleId: 'com.example.routemate',
  );
}
